---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	resume_parser(resume_parser)
	jd_analyzer(jd_analyzer)
	skill_matcher(skill_matcher)
	ats_scorer(ats_scorer)
	gap_analyzer(gap_analyzer)
	resume_rewriter(resume_rewriter)
	truth_checker(truth_checker)
	quality_reviewer(quality_reviewer)
	__end__([<p>__end__</p>]):::last
	__start__ --> resume_parser;
	ats_scorer --> gap_analyzer;
	gap_analyzer --> resume_rewriter;
	jd_analyzer --> skill_matcher;
	quality_reviewer -.-> __end__;
	quality_reviewer -.-> resume_rewriter;
	resume_parser --> jd_analyzer;
	resume_rewriter --> truth_checker;
	skill_matcher --> ats_scorer;
	truth_checker -.-> quality_reviewer;
	truth_checker -.-> resume_rewriter;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
